version: "3.0"

services:
 debezium-redis:
    image: debezium-redis
    build: 
      context: debezium-redis-demo/.
      dockerfile: Dockerfile
    ports:
      - 8082:8082
 postgres-db:
    build: 
      context: postgresql/.
      dockerfile: Dockerfile
    environment:
       - POSTGRES_PASSWORD=password
    ports:
      - 5435:5432
 redis:
    image: redis
    ports:
      - 6379:6379